# Generated by Django 5.2.12 on 2026-03-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='main_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='wedding.guest'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_type',
            field=models.CharField(choices=[('amigo', 'Amigo'), ('familia', 'Família'), ('crianca', 'Criança'), ('agregado', 'Agregado')], default='amigo', max_length=10),
        ),
        migrations.AlterField(
            model_name='guest',
            name='invited_by',
            field=models.CharField(choices=[('noivo', 'Noivo'), ('noiva', 'Noiva')], default='noivo', max_length=10),
        ),
    ]
